### ISSUE TITLE
Error : Method not found

### ISSUE THREAD

**Issue by aozurei** [imDema/FreeMove#12]
I cannot move anything from C:\ to another drive
It shows Method not found : '!!0[] System.Array.Empty()'.
What should i do? T_T

![20201006_200823](https://user-images.githubusercontent.com/71364698/95205663-e259ce00-080f-11eb-98bf-0941ca2fc339.png)

**Comment by imDema** [comment]
It seems like you are using an older version of Windows, which is not supported, since I have no way of building and running it.
If you can provide more details about the directories and help me replicate it I can look into it, but since I cannot get it to appear, there is not much that I can do with this little details.
I'll mark it as closed, will reopen if you want me to look into it
